---
title: "Data Visualization"
author: "Kiran Favre"
date: "2022-08-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(janitor)
library(here)

library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

library(gapminder)

#library(sf) -- will do later
```

### 

```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(color = "pink")
```

Create a histogram for total lengths of all lizards in data set

```{r}
histogram <- ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram(color = "blue", 
                 fill = "purple", 
                 size = 1, 
                 linetype = "dotted")

#if youre changing something based on a constant, it should not be within aes
```

```{r}
ggplot(lizards, aes( x = total_length,
                     y = weight)) +
  geom_point(
    shape = 7,
    color = "cyan4",
    fill = "pink",
    size = 4,
    alpha = 0.7
  )

#can change shape #1-100
#alpha is transparency: 0 is clear and 1 is opaque
#if you want to change colors based on variables: put in aes
```

```{r}
# things u want constant, put in geom_point. If you want things to change, put it in aes
ggplot(lizards, aes(x = total_length,
                    y = weight)) +
  geom_point(aes(color = common_name,
                 size = total_length,
                 alpha = 0.5)) + 
  theme_dark()

```

```{r}
# use facet wrap to help distinguish patterns across species
ggplot(lizards, aes(x = total_length,
                    y = weight)) +
  geom_point() +
  facet_wrap(~common_name, scales = "free")

#~ is "function of"
```

```{r}
#make a data table with total counts of lizards
# use "new name = n()
# n counts numbers of row

lizard_counts <- lizards |> 
  group_by(common_name) |> 
  summarize(
    counts = n()
  )

lizard_counts <- lizards |> 
  count(common_name)
```

Make a bar plot (column graph) that plots \# of lizards

```{r}
ggplot(lizard_counts, aes( y= fct_reorder(common_name, n),
                            x = n)) +
  geom_col()

#output gives horizontal bar chart in reverse alphabetical order
# to change this, we need to change the class of the species to factor so we can sort it
# use fct_reoder, then need to tell it where the variables are that we want to order it by (which is why we have y = fct_reorder(common_name, n))

```

Create scatter plots faceted by species for total length vs weight. The color and shape of points should differ based on species (common name). Change the theme, and make each faceted panel have flexible axes limits

```{r}
ggplot(lizards, aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name, shape = common_name),
             size = 1.5,
             alpha = 0.6) + 
  theme_grey() +
  facet_wrap(~common_name, scales = "free") +
  labs( x = "Total length(mm)",
        y = "weight (g)",
        title = "Jornada Basin lizard sizes",
        subtitle = "All lizards follow the standard weight-length relationship, with Western Whiptails being largest.",
        caption = "Data: Jornada Basin LTER, CCBY",
        )

#using shape only deals with 6 variables, you could 
```
